name: CI

on: [push, pull_request]

jobs:
  lint_test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install --upgrade hatch

      - run: hatch run black --check .

      - run: hatch run cov
